services:
  nginx:
    image: "$DOCKER_USERNAME/multi-nginx" # Docker username must be a secret stored on EB
    mem_limit: 128m
    # Can omit hostname since nginx does not have a server in the ./nginx/default.conf
    ports:
      - "80:80"
  server:
    image: "$DOCKER_USERNAME/multi-server"
    mem_limit: 128m
    hostname: api # Comes from ./nginx/default.conf
    environment: # Keys found in server/keys.js.
      - REDIS_HOST=$REDIS_HOST # References secret stored in Elastic Beanstalk EXCEPT port
      - REDIS_PORT=$REDIS_PORT # References secret stored in Elastic Beanstalk
      - PGUSER=$PGUSER # References secret stored in Elastic Beanstalk
      - PGHOST=$PGHOST # References secret stored in Elastic Beanstalk EXCEPT port
      - PGDATABASE=$PGDATABASE # References secret stored in Elastic Beanstalk
      - PGPASSWORD=$PGPASSWORD # References secret stored in Elastic Beanstalk
      - PGPORT=$PGPORT # References secret stored in Elastic Beanstalk
  client:
    image: "$DOCKER_USERNAME/multi-client"
    mem_limit: 128m
    hostname: client # Comes from ./nginx/default.conf
  worker:
    image: "$DOCKER_USERNAME/multi-worker"
    mem_limit: 128m
    # Can omit hostname since nginx does not have a server in the ./nginx/default.conf
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT





