apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
      - name: server
        image: rallycoding/multi-server
        env:
          - name: REDIS_HOST
            value: redis-cluster-ip-service
          - name: REDIS_PORT
            value: "6379"
          - name: PGUSER
            value: postgres
          - name: PGHOST
            value: postgres-cluster-ip-service
          - name: PGPORT
            value: "5432"
          - name: PGDATABASE
            value: postgres
          - name: PGPASSWORD
            valueFrom: # Indicates we are passing in this key from somewhere else rather than entering it directly.
              secretKeyRef:
                name: postgres-password # Name of key (`kubectl get secrets`).
                key: POSTGRES_PASSWORD # Key to pass in (as one secret can have multiple keys)
        ports:
        - containerPort: 5000
